[package]
name = "message-encoding"
version = "0.2.1"
edition = "2021"
license = "MIT"
description = "A simple trait to control how a structure should be encoded"
repository = "https://github.com/Developed-Methods/message-encoding"

[dependencies]
byteorder = "1.5"
